# Site settings
title: Diego Barros Araya
email: contact@diegobarrosaraya.com
description: >-
  Senior IT Engineer & Technical Consultant. With expertise in cloud-native environments, 
  Docker, OCI, embedded systems, and Atlassian products.
baseurl: ""
url: "https://diegobarrosaraya.com"
github_username: DiegoBarrosA
linkedin_username: diegobarrosaraya

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Custom variables
author:
  name: Diego Barros Araya
  email: contact@diegobarrosaraya.com
  linkedin: https://linkedin.com/in/diegobarrosaraya
  github: https://github.com/DiegoBarrosA
  blog: https://blog.diegobarrosaraya.com
  docs: https://docs.diegobarrosaraya.com

# Assets
assets_repo: https://diegobarrosa.github.io/diegobarrosaraya-assets
resume_repo: https://api.github.com/repos/DiegoBarrosA/diego-barros-resume-generator/contents/docs/resume.md