name: Update Resume from Generator

on:
  schedule:
    # Run daily at 7 AM UTC (after resume generator runs)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allow manual triggering
  repository_dispatch:
    types: [resume-updated]

jobs:
  update-resume:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests
        
    - name: Update resume content
      run: python3 update_resume.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.md
        git diff --staged --quiet || git commit -m "Auto-update resume from generator repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}